name: Daily Script

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:  # This allows the workflow to be manually triggered

jobs:
  telegram-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
  
      - name: Run the script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_SESSION_STRING: ${{ secrets.TELEGRAM_SESSION_STRING }}
          POE_PB_TOKEN: ${{ secrets.POE_PB_TOKEN }}
          POE_CHAT_CODE: ${{ secrets.POE_CHAT_CODE }}
        run: python telegram_digest/main.py
        
      - name: Upload Log File
        uses: actions/upload-artifact@v2
        with:
          name: bot.log
          path: ./bot.log
